logger:
  default: info

mqtt:
  enabled: false

detectors:
  cpu:
    type: cpu

objects:
  track:
    - person
    - car
    - dog
    - cat
    - bird
  filters:
    person:
      min_area: 1500
      max_area: 100000
      min_score: 0.7
      threshold: 0.85

cameras:
  tapo_c222:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp -i
      inputs:
        - path: rtsp://ardatiryaki:Arda0404%21@192.168.1.11/stream1
          roles:
            - detect
            - record
    snapshots:
      enabled: true
      clean_copy: true
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    detect:
      enabled: true
      width: 320
      height: 240
      fps: 5

database:
  path: /config/frigate.db
