logger:
  default: info

mqtt:
  enabled: false

detectors:
  cpu:
    type: cpu

objects:
  track:
    - person
    - car
    - dog
    - cat
    - bird
  filters:
    person:
      threshold: 0.7

cameras:
  tapo_c222:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_IP}:554/stream1
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_RTSP_IP}:554/stream2
          roles:
            - detect
    snapshots:
      enabled: true
      clean_copy: true
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10
    zones:
      desk:
        coordinates: 0.597,0.827,0.889,0.857,0.927,1,0.597,1
        inertia: 3
        loitering_time: 0
      bed:
        coordinates: 0.283,0.654,0.547,0.705,0.5,1,0.03,1,0.135,0.822

        inertia: 3
        loitering_time: 0
database:
  path: /config/frigate.db
detect:
  enabled: true
version: 0.16-0
